/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf -o src/components/House.jsx -k -K -r public 
Author: Progressive Dreamer (https://sketchfab.com/dbtjdwns0000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/korean-house-b53e26cbe77046cf8e0eba55f90a0877
Title: Korean House
*/

import React, { useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { currentPageAtom } from "./UI";
import { degToRad } from "three/src/math/MathUtils";
import { useAtom } from "jotai";

const OverlayItem = ({
  className = "",
  title,
  description,
  bgColor,
  ...props
}) => {
  const [currentPage] = useAtom(currentPageAtom);
  return (
    <Html
      transform
      distanceFactor={1.2}
      center
      className={`w-48 rounded-md overflow-hidden ${
        currentPage === "store" ? "" : "opacity-0"
      } transition-opacity duration-1000 ${className}`}
      {...props}
    >
      <div className="bg-white bg-opacity-50 backdrop-blur-lg text-xs p-2 w-full">
        <h2 className="font-bold">{title}</h2>
        <p>{description}</p>
      </div>
      <button
        className={`${bgColor} hover:bg-opacity-50 transition-colors duration-500 px-4 py-2 font-bold text-white w-full text-xs`}
      >
        Add to cart
      </button>
    </Html>
  );
};
export function House(props) {
  const { nodes, materials } = useGLTF("/models/scene.gltf");
  const [isOverlayVisible, setOverlayVisible] = useState(false);

  const handleGroupClick = () => {
    console.log("clicked");
    setOverlayVisible(!isOverlayVisible);
  };
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="72ee2e010dd9444ba3f58050c015dec4fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="RootNode">
              <group
                name="wdst_low"
                position={[0, -188.105, 204.147]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="wdst_low_Material__2_0"
                  geometry={nodes.wdst_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="wdl01_low"
                position={[0, 156.388, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="wdl01_low_Material__2_0"
                  geometry={nodes.wdl01_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="wdl02_low"
                position={[0, 65.223, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="wdl02_low_Material__2_0"
                  geometry={nodes.wdl02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="stl01_low"
                position={[0, 77.82, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="stl01_low_Material__2_0"
                  geometry={nodes.stl01_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="stl02_low"
                position={[0, 35.643, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="stl02_low_Material__2_0"
                  geometry={nodes.stl02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="ling_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="ling_low_Material__2_0"
                  geometry={nodes.ling_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="body_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="body_low_Material__2_0"
                  geometry={nodes.body_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="wd01_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="wd01_low_Material__2_0"
                  geometry={nodes.wd01_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="wd02_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="wd02_low_Material__2_0"
                  geometry={nodes.wd02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="wd03_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="wd03_low_Material__2_0"
                  geometry={nodes.wd03_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="wd04_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="wd04_low_Material__2_0"
                  geometry={nodes.wd04_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="dr01_low"
                position={[0, -111.852, 95.582]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="dr01_low_Material__2_0"
                  geometry={nodes.dr01_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="dr02_low"
                position={[0, -60.883, 93.56]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="dr02_low_Material__2_0"
                  geometry={nodes.dr02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>

              <group
                onClick={handleGroupClick}
                name="dr03_low"
                position={[0, -121.429, 91.907]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="dr03_low_Material__2_0"
                  geometry={nodes.dr03_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />

                {isOverlayVisible && (
                  <OverlayItem
                    rotation-y={degToRad(20)}
                    position-x={-2}
                    position-z={-10}
                    position-y={95}
                    title={"door"}
                    description={"doorr"}
                    bgColor={"bg-yellow-500"}
                    className={"transition delay-1000"}
                  />
                )}
              </group>
              <group
                name="dr04_low"
                position={[0, -120.549, 91.648]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="dr04_low_Material__2_0"
                  geometry={nodes.dr04_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="st01_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="st01_low_Material__2_0"
                  geometry={nodes.st01_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="wd01_low_1"
                position={[0, -189.308, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="wd01_low_Material__2_0_1"
                  geometry={nodes.wd01_low_Material__2_0_1.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="body02_low"
                position={[0, -155.076, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="body02_low_Material__2_0"
                  geometry={nodes.body02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="st02_low"
                position={[0, -2.637, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="st02_low_Material__2_0"
                  geometry={nodes.st02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="st03_low"
                position={[0, -76.386, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="st03_low_Material__2_0"
                  geometry={nodes.st03_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="hd01_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="hd01_low_Material__2_0"
                  geometry={nodes.hd01_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="hd02_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="hd02_low_Material__2_0"
                  geometry={nodes.hd02_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="hd03_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="hd03_low_Material__2_0"
                  geometry={nodes.hd03_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="st04_low"
                position={[0, -208.238, 310.756]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="st04_low_Material__2_0"
                  geometry={nodes.st04_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="stairs_low"
                position={[0, -205.475, 309.466]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="stairs_low_Material__2_0"
                  geometry={nodes.stairs_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="wdf_low" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="wdf_low_Material__2_0"
                  geometry={nodes.wdf_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="wd05_low"
                position={[0, 16.455, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="wd05_low_Material__2_0"
                  geometry={nodes.wd05_low_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="ling_low002"
                position={[-0.956, 135.104, 294.491]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="ling_low002_Material__2_0"
                  geometry={nodes.ling_low002_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group name="ling_low003" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="ling_low003_Material__2_0"
                  geometry={nodes.ling_low003_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
              <group
                name="ling_low004"
                position={[-0.956, 151.543, 306.266]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="ling_low004_Material__2_0"
                  geometry={nodes.ling_low004_Material__2_0.geometry}
                  material={materials.Material__2}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/scene.gltf");
