/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/news.glb 
Author: billito20055 (https://sketchfab.com/billito20055)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/newspaper-package-d9abf2a45b4e449c9c1e3c0a4ee06e2f
Title: Newspaper package
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function News(props) {
  const { nodes, materials } = useGLTF("./models/news.glb");
  const meshRef = useRef();

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.886}>
        <mesh
          ref={meshRef}
          geometry={nodes.Object_2.geometry}
          material={materials.Publisidad_2}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Publisidad_2}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/news.glb");
